" use pathogen for plugins
execute pathogen#infect()
syntax on
filetype plugin indent on

set ruler
set number

let no_buffers_menu=1
set term=xterm-256color
set background=dark
let g:solarized_termcolors=256
try
    colorscheme solarized
catch /^Vim\%((\a\+)\)\=:E185/
    " ignore colorscheme if not exists
endtry


" Better command line completion 
set wildmenu

"" Tabs. May be overridden by autocmd rules
set tabstop=4
set softtabstop=0
set shiftwidth=4
set expandtab
"" Fix backspace indent
set backspace=indent,eol,start

set noswapfile

" status line
set laststatus=2

" vim-go
let g:go_highlight_types = 1
let g:go_highlight_fields= 1
let g:go_highlight_functions= 1
let g:go_highlight_function_calls= 1

"tagbar for go
let g:tagbar_type_go = {
    \ 'ctagstype' : 'go',
	\ 'kinds'     : [
		\ 'p:package',
		\ 'i:imports:1',
		\ 'c:constants',
		\ 'v:variables',
		\ 't:types',
		\ 'n:interfaces',
		\ 'w:fields',
		\ 'e:embedded',
		\ 'm:methods',
		\ 'r:constructor',
		\ 'f:functions'
	\ ],
	\ 'sro' : '.',
	\ 'kind2scope' : {
		\ 't' : 'ctype',
		\ 'n' : 'ntype'
	\ },
	\ 'scope2kind' : {
		\ 'ctype' : 't',
		\ 'ntype' : 'n'
	\ },
	\ 'ctagsbin'  : 'gotags',
	\ 'ctagsargs' : '-sort -silent'
\ }

nmap <F2> :NERDTreeTabsToggle<CR>
nmap <F8> :TagbarToggle<CR>
